{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.database" . }}"
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.database.internal.service.port }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: database
{{- end -}}