apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.core" . }}
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.core.service.port }}
      targetPort: {{ .Values.core.service.targetPort }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: core
