apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "harbor.core" . }}
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: core
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: core
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
{{ include "harbor.matchLabels" . | indent 8 }}
        component: core
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/core/core-cm.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/core/core-secret.yaml") . | sha256sum }}
{{- if .Values.core.podAnnotations }}
{{ toYaml .Values.core.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: core
        image: {{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: {{ .Values.core.livenessProbe.httpGet.path }}
            port: {{ .Values.core.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.core.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.core.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.core.readinessProbe.httpGet.path }}
            port: {{ .Values.core.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.core.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.core.readinessProbe.periodSeconds }}
        env:
          - name: CORE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "harbor.core" . }}
                key: secret
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ template "harbor.jobservice" . }}"
                key: secret
          - name: _REDIS_URL
            value: {{ template "harbor.redisForCore" . }}
          - name: _REDIS_URL_REG
            value: {{ template "harbor.redisForGC" . }}
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          - name: CONFIG_PATH
            value: /etc/core/app.conf
          - name: SYNC_REGISTRY
            value: "false"
          - name: ADMINSERVER_URL
            value: "http://{{ template "harbor.adminserver" . }}"
          - name: CHART_CACHE_DRIVER
            value: "redis"
        ports:
        - containerPort: {{ .Values.core.ports.containerPort }}
        volumeMounts:
        - name: config
          mountPath: /etc/core/app.conf
          subPath: app.conf
        - name: secret-key
          mountPath: /etc/core/key
          subPath: key
        - name: token-service-private-key
          mountPath: /etc/core/private_key.pem
          subPath: tokenServicePrivateKey
        {{- if eq (include "harbor.autoGenCert" .) "true" }}
        - name: ca-download
          mountPath: /etc/core/ca/ca.crt
          subPath: ca.crt
        {{- end }}
        - name: psc
          mountPath: /etc/core/token
      volumes:
      - name: config
        configMap:
          name: {{ template "harbor.core" . }}
      - name: secret-key
        secret:
          secretName: {{ template "harbor.core" . }}
          items:
            - key: secretKey
              path: key
      - name: token-service-private-key
        secret:
          secretName: {{ template "harbor.core" . }}
      {{- if eq (include "harbor.autoGenCert" .) "true" }}
      - name: ca-download
        secret:
        {{- if eq (include "harbor.autoGenCertForIngress" .) "true" }}
          secretName: "{{ template "harbor.ingress" . }}"
        {{- else }}
          secretName: {{ template "harbor.nginx" . }}
        {{- end }}
          items:
            - key: ca.crt
              path: ca.crt
      {{- end }}
      - name: psc
        emptyDir: {}
    {{- with .Values.core.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.core.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.core.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
