apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.jobservice.service.port }}
      targetPort: {{ .Values.jobservice.service.targetPort }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: jobservice
