# Default values for phpfpm-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: test3
replicaCount: 2
strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
#minReadySeconds: 5
revisionHistoryLimit: 10
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  port: 80
  protocol: TCP
  nodePort: 31555
terminationGracePeriodSeconds: 10
liveness:
  tcpSocket:
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 1
readiness:
  tcpSocket:
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 1
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local