apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
  namespace: test1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: harbor:30002/library/nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: test1
  labels:
    app: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: my-nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nginx
  namespace: test1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: node.test.local
    http:
      paths:
      - path: /
        backend:
          serviceName: my-nginx
          servicePort: 80