apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.registry" . }}"
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: registry
      port: {{ .Values.registry.service.registryport }}
    - name: controller
      port: {{ .Values.registry.service.controllerport }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry