apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.adminserver" . }}"
  namespace: harbor
spec:
  ports:
    - port: {{ .Values.adminserver.service.port }}
      targetPort: {{ .Values.adminserver.service.targetPort }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: adminserver