apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}-nginx
    version: 0.1.0
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "fullname" . }}-nginx