{{- if eq .Values.redis.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.redis" . }}
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: redis
{{- end -}}