apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: my-nginx
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    name: http
  selector:
    app: my-nginx