{{ if .Values.notary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.notary-server" . }}
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.notary.service.serverport }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: notary-server

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.notary-signer" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.notary.service.signerport }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: notary-signer
{{ end }}