{{ if .Values.clair.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "harbor.clair" . }}
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: clair
spec:
  replicas: {{ .Values.clair.replicas }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: clair
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: clair
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/clair/clair-cm.yaml") . | sha256sum }}
{{- if .Values.clair.podAnnotations }}
{{ toYaml .Values.clair.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: clair
        image: {{ .Values.clair.image.repository }}:{{ .Values.clair.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: {{ .Values.clair.livenessProbe.httpGet.path }}
            port: {{ .Values.clair.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.clair.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.clair.livenessProbe.periodSeconds}}
        readinessProbe:
          httpGet:
            path: {{ .Values.clair.readinessProbe.httpGet.path }}
            port: {{ .Values.clair.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.clair.readinessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.clair.readinessProbe.periodSeconds}}
        args: ["-log-level", "{{ .Values.logLevel }}"]
        env:
        {{- if .Values.clair.httpProxy }}
        - name: HTTP_PROXY
          value: {{ .Values.clair.httpProxy }}
        {{- end }}
        {{- if .Values.clair.httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.clair.httpsProxy }}
        {{- end }}
        - name: NO_PROXY
          value: "{{ template "harbor.registry" . }},{{ template "harbor.core" . }}"
        resources:
{{ toYaml .Values.clair.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.clair.ports.containerPort }}
        volumeMounts:
        - name: clair-config
          mountPath: /etc/clair/config.yaml
          subPath: config.yaml
      volumes:
      - name: clair-config
        configMap:
          name: "{{ template "harbor.clair" . }}"
          items:
            - key: config.yaml
              path: config.yaml
    {{- with .Values.clair.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.clair.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.clair.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
