{{ if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.clair" . }}"
  namespace: harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.clair.service.port }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: clair
{{ end }}
